### ISSUE TITLE
Installation successful on Windows 10. Python 3.6.8.

### ISSUE THREAD

**Issue by leefeel** [memo/webcam-pix2pix-tensorflow#5]
After many conflicts installing opencv3, I wanted to share this configuration working on Windows 10:
CUDA 10.0.132
NVidia 417.35
cudnn64_7.dll
opencv 4.1.0
tensorflow-gpu 1.13.1
numpy 1.16.3
python 3.6.8

Opencv3 is not available at menpo anymore:
conda install -c menpo opencv3

For my configuration it worked following this installation of opencv:
pip install opencv-python
pip install opencv-contrib-python

**Comment by memoakten** [comment]
thanks for the update!

**Comment by skabbit** [comment]
Also works with tensorflow-gpu 1.14.0
